[solution]
name = "moe-solution-v0"      # Solution name
definition = "moe_fp8_block_scale_ds_routing_topk8_ng8_kg4_e32_h7168_i2048"          # Track: fused_moe | sparse_attention | gated_delta_net
author = "Hetu@PKU"              # Team/author name

[build]
language = "triton"               # triton | cuda
entry_point = "main.py::fused_moe"            # Kernel function name
destination_passing_style = false
